
services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db



  postgres:
    image: timescale/timescaledb:2.15.2-pg15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: analyticsdb
    ports:
      - "5433:5432"


  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: always
    ports:
      - "1880:1880"   # Node-RED UI
    volumes:
      - nodered_data:/data
    depends_on:
      - redis
      - mqtt
      - postgres
    environment:
      - TZ=Asia/Kolkata 


volumes:
  mongo_data:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
  nodered_data: